[build]
builder = "railpack"

[variables]
PORT = "8080"

[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.intl",
  "php82Extensions.zip",
  "nodejs_22"
]

[phases.install]
commands = [
  "composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader",
  "npm ci"
]

[phases.build]
commands = [
  "npm run build"
]

[start]
command = "php artisan serve --host 0.0.0.0 --port ${PORT}"
